"""
lab_kit.py  --  provided support code for Lab 05 (Instruction-Based Prompting).

Students do NOT edit this file. It supplies:
  - a deterministic, OFFLINE simulated model whose OUTPUT QUALITY depends on
    how well the prompt is written (no network, no API key, fully reproducible),
  - a prompt renderer that assembles tagged sections in canonical order,
  - a soft grader (check / run_check) used by the notebook self-tests.

Design note for the instructor:
  simulate_model() wraps a competent triage reasoner. The reasoner always
  computes the correct decision. What DEGRADES with a weak prompt is only the
  FORMATTING and CONTRACT-CONFORMANCE of the emitted text, mirroring how real
  models drift when instructions are underspecified.
"""
from __future__ import annotations
import json
import re
from typing import Any, Callable

# --------------------------------------------------------------------------
# Canonical prompt section order (used by the renderer and the linter task).
# --------------------------------------------------------------------------
REQUIRED_SECTIONS = [
    "ROLE", "INSTRUCTION", "CONTEXT", "STEP_LIST", "CONSTRAINTS",
    "OUTPUT_CONTRACT", "INPUTS", "ACCEPTANCE_TESTS", "SELF_VERIFY",
]


def render_prompt(sections: dict[str, str]) -> str:
    """Render a section dict into <TAG>...</TAG> blocks in canonical order.

    Only sections present in the dict are emitted. Unknown keys are ignored
    so the renderer never invents structure the author did not ask for.
    """
    blocks = []
    for tag in REQUIRED_SECTIONS:
        if tag in sections and sections[tag] is not None:
            body = str(sections[tag]).strip("\n")
            blocks.append(f"<{tag}>\n{body}\n</{tag}>")
    return "\n\n".join(blocks)


# --------------------------------------------------------------------------
# Ground-truth features for each synthetic case. The simulated model reasons
# from these; students never see them (they live in the provided kit).
# --------------------------------------------------------------------------
CASE_FEATURES: dict[str, dict[str, Any]] = {
    "C-101": {"days": 12, "product_class": "power_tool", "opened": True,
              "receipt_missing": False, "custom_prepared": False, "accessory_missing": False},
    "C-102": {"days": 7, "product_class": "shelving", "opened": False,
              "receipt_missing": True, "custom_prepared": False, "accessory_missing": False},
    "C-103": {"days": 5, "product_class": "custom_paint", "opened": True,
              "receipt_missing": False, "custom_prepared": True, "accessory_missing": False},
    "C-104": {"days": 45, "product_class": "patio_heater", "opened": True,
              "receipt_missing": False, "custom_prepared": False, "accessory_missing": False,
              "hardware_fault": True, "under_warranty": True},
    "C-105": {"days": 10, "product_class": "light_fixture", "opened": True,
              "receipt_missing": False, "custom_prepared": False, "accessory_missing": True},
}

WINDOW_DAYS = 30
RESTOCK_FEE_PERCENT = 15


def _reason_record(cid: str, f: dict[str, Any]) -> dict[str, Any]:
    """Apply the Timberline policy to one case's features -> canonical record."""
    within = f["days"] <= WINDOW_DAYS

    # Rule 4: custom-prepared items are non-returnable once prepared.
    if f.get("custom_prepared"):
        return {"input_id": cid, "eligibility": "ineligible", "action": "deny",
                "fee_percent": None,
                "reasons": ["Custom-mixed paint is non-returnable once prepared"],
                "policy_lines": ["4"]}

    # Rule 6: window expired + hardware fault under warranty -> warranty repair.
    if not within and f.get("hardware_fault") and f.get("under_warranty"):
        return {"input_id": cid, "eligibility": "ineligible", "action": "warranty_repair",
                "fee_percent": None,
                "reasons": ["Return window expired", "Item has an active manufacturer warranty"],
                "policy_lines": ["1", "6"]}

    # Rule 5: receipt missing within window -> account lookup.
    if within and f.get("receipt_missing"):
        return {"input_id": cid, "eligibility": "needs_lookup", "action": "lookup",
                "fee_percent": None,
                "reasons": ["Receipt missing", "Offer lookup by email and last four card digits"],
                "policy_lines": ["5"]}

    # Rule 3: opened power tool within window -> partial refund with restocking fee.
    if within and f["product_class"] == "power_tool" and f.get("opened"):
        return {"input_id": cid, "eligibility": "eligible", "action": "partial_refund",
                "fee_percent": RESTOCK_FEE_PERCENT,
                "reasons": ["Opened power tool within return window", "15 percent restocking fee applies"],
                "policy_lines": ["1", "3"]}

    # Rule 2: missing accessory within window -> partial refund (no full refund).
    if within and f.get("accessory_missing"):
        return {"input_id": cid, "eligibility": "eligible", "action": "partial_refund",
                "fee_percent": None,
                "reasons": ["Original accessory missing", "Full refund requires all accessories"],
                "policy_lines": ["2"]}

    # Default within window, resellable -> full refund.
    if within:
        return {"input_id": cid, "eligibility": "eligible", "action": "refund",
                "fee_percent": None,
                "reasons": ["Within return window and in resellable condition"],
                "policy_lines": ["1", "2"]}

    # Fallback: expired, no warranty path.
    return {"input_id": cid, "eligibility": "ineligible", "action": "deny",
            "fee_percent": None,
            "reasons": ["Return window expired"],
            "policy_lines": ["1"]}


# --------------------------------------------------------------------------
# Prompt-quality signals. Tolerant regexes: there is no single magic string.
# A well-written prompt satisfies each concept; phrasing is up to the author.
# --------------------------------------------------------------------------
def _has_json_only(p: str) -> bool:
    return bool(re.search(r"only\s+json|strict\s+json|<OUTPUT_CONTRACT>", p, re.I))

def _has_numeric_fee(p: str) -> bool:
    # Some rule tying the fee field to a numeric type.
    return bool(re.search(r"fee[_\s]*percent[^.\n]{0,60}(number|numeric|integer)", p, re.I)
                or re.search(r"(number|numeric|integer)[^.\n]{0,60}fee", p, re.I))

def _has_citation(p: str) -> bool:
    return bool(re.search(r"cite[^.\n]{0,40}policy|policy[_\s]*lines?[^.\n]{0,40}(cite|line numbers?)", p, re.I))

def _has_reasons_rule(p: str) -> bool:
    return bool(re.search(r"reasons?[^.\n]{0,60}(non[-\s]?empty|at least one|grounded|specific|policy)", p, re.I))


def simulate_model(prompt: str, messages: list[dict[str, str]]) -> str:
    """Deterministic offline stand-in for a hosted LLM.

    Returns a STRING (as a real completion would). Formatting quality is a pure
    function of the prompt: underspecified prompts yield non-conformant text.
    """
    records = [_reason_record(m["id"], CASE_FEATURES[m["id"]]) for m in messages]

    json_only = _has_json_only(prompt)
    numeric_fee = _has_numeric_fee(prompt)
    citation = _has_citation(prompt)
    reasons_rule = _has_reasons_rule(prompt)

    out_records = []
    for r in records:
        rec = dict(r)
        if not numeric_fee and rec["fee_percent"] is not None:
            rec["fee_percent"] = f"{rec['fee_percent']}%"      # wrong type: string
        if not citation:
            rec["policy_lines"] = []                            # dropped citations
        if not reasons_rule:
            rec["reasons"] = []                                 # dropped rationale
        if not json_only:
            rec["disclaimer"] = "Please verify with a supervisor."  # stray field
        out_records.append(rec)

    doc = {"records": out_records, "stats": {"count": len(out_records)}}
    payload = json.dumps(doc, indent=2)

    if not json_only:
        # Chatty, fenced output that strict json.loads() will reject.
        return ("Sure! Here is my analysis of each customer message:\n\n"
                "```json\n" + payload + "\n```\n\n"
                "Let me know if you would like any adjustments.")
    return payload


# --------------------------------------------------------------------------
# Soft grader used by the notebook self-tests.
# --------------------------------------------------------------------------
class Grader:
    def __init__(self) -> None:
        self.passed = 0
        self.failed = 0
        self.rows: list[tuple[bool, str, str]] = []

    def check(self, name: str, cond: bool, detail: str = "") -> bool:
        ok = bool(cond)
        self.passed += ok
        self.failed += (not ok)
        self.rows.append((ok, name, detail))
        mark = "PASS" if ok else "FAIL"
        line = f"[{mark}] {name}"
        if not ok and detail:
            line += f"  ->  {detail}"
        print(line)
        return ok

    def run_check(self, name: str, fn: Callable[[], Any], expect_error: bool = False) -> bool:
        try:
            fn()
            return self.check(name, not expect_error,
                              "" if not expect_error else "expected an error, none raised")
        except NotImplementedError:
            return self.check(name, False, "not implemented yet")
        except Exception as e:  # noqa: BLE001
            return self.check(name, expect_error,
                              "" if expect_error else f"{type(e).__name__}: {e}")

    def summary(self) -> str:
        total = self.passed + self.failed
        return f"{self.passed}/{total} checks passed, {self.failed} failing"
